version: '3.8'

services:
  # Service DB
  postgres:
    image: postgres:15-alpine
    container_name: payment-postgres
    restart: always
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: payment-engine-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/payment_db
      DB_USERNAME: postgres
      DB_PASSWORD: password

volumes:
  pg_data: